tasks:
  - before: |
      rm -rf $HOME/.cargo
      unset CARGO_HOME
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source $HOME/.cargo/env
      echo 'export CARGO_HOME="$HOME/.cargo"' >> ~/.bashrc
      source ~/.bashrc
      export TEMP_DIR=$(mktemp -d)
      curl -L https://github.com/WebAssembly/binaryen/releases/download/version_113/binaryen-version_113-x86_64-linux.tar.gz | tar -xzC $TEMP_DIR
      sudo cp -vf $TEMP_DIR/binaryen-version_113/bin/wasm-opt /usr/bin/

    init: |
      gp open rmrk-token/src/lib.rs
      clear && printf '\e[3J' && history -c

vscode:
  extensions:
    - matklad.rust-analyzer
