[package]
name = "types"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gstd = { workspace = true, features = ["debug"] }
primitive-types = { workspace = true, features = ["scale-info"] }
